export const mockUser = {
  "login": "WladyslawK",
  "id": 64751494,
  "node_id": "MDQ6VXNlcjY0NzUxNDk0",
  "avatar_url": "https://avatars.githubusercontent.com/u/64751494?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/WladyslawK",
  "html_url": "https://github.com/WladyslawK",
  "followers_url": "https://api.github.com/users/WladyslawK/followers",
  "following_url": "https://api.github.com/users/WladyslawK/following{/other_user}",
  "gists_url": "https://api.github.com/users/WladyslawK/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/WladyslawK/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/WladyslawK/subscriptions",
  "organizations_url": "https://api.github.com/users/WladyslawK/orgs",
  "repos_url": "https://api.github.com/users/WladyslawK/repos",
  "events_url": "https://api.github.com/users/WladyslawK/events{/privacy}",
  "received_events_url": "https://api.github.com/users/WladyslawK/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Władysław Kurczenko",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 18,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2020-05-03T19:56:37Z",
  "updated_at": "2023-02-11T10:42:58Z"
}